In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\amolk\archive (3)\IMDB Dataset.csv")

In [3]:
df.head()
#df.shape

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df['review'] = df['review'].str.lower()
    

In [5]:
import string

In [6]:
exclude  = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', exclude))   

In [7]:
df['review'] = df['review'].apply(remove_punctuation)

In [8]:
import nltk
from nltk.corpus import stopwords
import re

In [9]:
stopword = set(stopwords.words('english'))

In [10]:
def remove_stopwords(text):
    text = text.split()
    
    filter = [word for word in text if word.lower() not in stopword]
    return " ".join(filter)

In [11]:
from nltk.tokenize import word_tokenize

In [12]:
df['tokenized_description'] = df['review'].apply(lambda x: word_tokenize(x))

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv = CountVectorizer(max_features=3000)

In [38]:
final_df = cv.fit_transform(df['review']).toarray()

In [39]:
final_df.shape

(50000, 3000)

In [41]:
final_df

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(df['sentiment'])

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(final_df, y, test_size=0.2,random_state=1)

In [48]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [50]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test, y_pred)

0.8425

In [51]:
import os

In [52]:
os.getcwd()

'C:\\Users\\amolk'